
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: bulent
  password: bulent
  host: localhost

development:
  <<: *default
  database:  e_commerce_development


# development:
#   host: 172.104.142.218
#   adapter: postgis
#   encoding: unicode
#   database: modaltrans_test_230914
#   pool: 5
#   username: modaltrans_dbadmin
#   password: nmbdbadmin

